# Generated by Django 3.2.8 on 2021-10-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='project_perfomance',
        ),
    ]
