# Generated by Django 3.2.8 on 2021-10-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_project_review_project_perfomance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
