# Generated by Django 3.2.8 on 2021-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211024_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Content',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='average',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
