# Generated by Django 3.2.8 on 2021-10-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='average',
            field=models.FloatField(blank=True, default=['mean']),
        ),
    ]
