# Generated by Django 3.2.8 on 2021-10-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211024_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_name',
        ),
    ]
