# Generated by Django 3.2.8 on 2021-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_review_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average',
        ),
        migrations.AlterField(
            model_name='review',
            name='Content',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='Design',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='Usability',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=1),
        ),
    ]
