# Generated by Django 3.2.8 on 2021-10-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_project_review_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project_name',
            new_name='project',
        ),
    ]
