# Generated by Django 3.2.8 on 2021-10-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_project_name_review_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='project_name',
        ),
    ]
