# Generated by Django 3.2.8 on 2021-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211029_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
