# Generated by Django 3.2.8 on 2021-10-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_review_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average',
        ),
    ]
